Repository o3de/o3de-atom-sampleviewer, pull requests merged in 2022-03, with the labels that each got.

#350 Create precheckin wizard widget.
  Gem/Code/Source/Automation/PrecommitWizardSettings.h
  Gem/Code/Source/Automation/ScriptManager.cpp
  Gem/Code/Source/Automation/ScriptManager.h
  Gem/Code/Source/Automation/ScriptReporter.cpp
  Gem/Code/Source/Automation/ScriptReporter.h
  Gem/Code/Source/SampleComponentManager.cpp
  Gem/Code/atomsampleviewergem_private_files.cmake
Labels: sig/graphics-audio

#358 Fix crash when trying to open beyond compare
  Gem/Code/Source/Platform/Mac/Utils_Mac.cpp
Labels: sig/graphics-audio

#366 Added a new screenshot test in ParallaxTest.bv.lua for a specific cam…
  Scripts/ExpectedScreenshots/ParallaxTest/screenshot_11_problematicAngle.png
  Scripts/ParallaxTest.bv.lua
Labels: sig/graphics-audio

#368 Enable NativeUI if ASV standalone is not in test mode.
  Standalone/Platform/Common/AtomSampleViewerApplication.cpp
  Standalone/Platform/Common/AtomSampleViewerApplication.h
Labels: feature/graphics/rpi

#376 Fixed AP scan folder issue
  Gem/Code/enabled_gems.cmake
Labels: sig/graphics-audio, feature/graphics

#378 Tentative Mac build fix for ASV
  Gem/Code/Source/ReadbackExampleComponent.cpp
Labels: sig/graphics-audio

#367 Add settings to sort script reporter screenshots by threshold
  Gem/Code/Source/Automation/PrecommitWizardSettings.h
  Gem/Code/Source/Automation/ScriptManager.cpp
  Gem/Code/Source/Automation/ScriptReporter.cpp
  Gem/Code/Source/Automation/ScriptReporter.h
Labels: sig/graphics-audio

#389 Atom Tools: removing shadow catcher opacity from lighting presets
  Gem/Code/Source/CommonSampleComponentBase.cpp
Labels: sig/graphics-audio, feature/graphics
